package com.localdownloader.domain.models

import kotlinx.serialization.Serializable

/**
 * Metadata representing a subtitle or caption stream available for media.
 */
@Serializable
data class SubtitleTrack(
    val code: String,
    val name: String? = null,
    val extension: String? = null,
    val url: String? = null,
    val isAutoGenerated: Boolean = false,
) {
    val displayName: String
        get() = name?.takeIf { it.isNotBlank() } ?: code

    val isOriginal: Boolean
        get() = !isAutoGenerated || code.endsWith("-orig") || code.contains("orig")
}
