package com.localdownloader.media.lyrics

import android.content.Context
import android.net.Uri
import com.localdownloader.domain.models.MusicLibraryTrack
import java.io.File
import java.util.Locale

object LyricsResolver {

    private val SUPPORTED_LYRICS_EXTENSIONS = setOf(
        "lrc", "srt", "vtt", "webvtt", "ass", "ssa", "txt"
    )

    fun discoverLyricsTracks(
        track: MusicLibraryTrack,
        explicitPaths: List<String> = emptyList(),
    ): List<LyricsTrackOption> {
        val candidates = mutableListOf<File>()

        // 1. Explicit paths from DownloadTask
        for (path in explicitPaths) {
            if (path.isNotBlank()) {
                val f = File(path)
                if (f.exists() && f.isFile && f.extension.lowercase() in SUPPORTED_LYRICS_EXTENSIONS) {
                    candidates.add(f)
                }
            }
        }

        // 2. Discover sibling files matching the track stem
        val filePath = track.filePath ?: track.playbackUri.takeIf { !it.startsWith("content://") }
        if (!filePath.isNullOrBlank()) {
            val audioFile = File(filePath)
            val parentDir = audioFile.parentFile
            val stem = audioFile.nameWithoutExtension
            if (parentDir != null && parentDir.exists() && stem.isNotBlank()) {
                val siblings = parentDir.listFiles()
                    ?.filter { candidate ->
                        candidate.isFile &&
                            candidate.name.startsWith("$stem.") &&
                            candidate.name != audioFile.name &&
                            candidate.extension.lowercase() in SUPPORTED_LYRICS_EXTENSIONS
                    }
                    ?.sortedBy { file ->
                        // Prioritize LRC, then VTT, then SRT
                        when (file.extension.lowercase()) {
                            "lrc" -> 0
                            "vtt", "webvtt" -> 1
                            "srt" -> 2
                            else -> 3
                        }
                    }
                    .orEmpty()
                candidates.addAll(siblings)
            }
        }

        val distinctFiles = candidates.distinctBy { it.absolutePath }
        if (distinctFiles.isEmpty()) return emptyList()

        val stem = track.filePath?.let { File(it).nameWithoutExtension } ?: track.fileName?.substringBeforeLast('.') ?: ""

        return distinctFiles.mapIndexed { index, file ->
            val label = buildTrackLabel(stem, file)
            val lang = extractLanguageCode(stem, file)
            val isAuto = file.name.contains("auto", ignoreCase = true) || file.name.contains("orig", ignoreCase = true)
            LyricsTrackOption(
                id = file.absolutePath,
                label = label,
                filePath = file.absolutePath,
                language = lang,
                isAutoGenerated = isAuto,
            )
        }
    }

    suspend fun loadLyrics(
        context: Context,
        pathOrUri: String,
        formatHint: String? = null,
    ): LyricsDocument {
        return runCatching {
            val content = if (pathOrUri.startsWith("content://")) {
                val uri = Uri.parse(pathOrUri)
                context.contentResolver.openInputStream(uri)?.use { stream ->
                    stream.bufferedReader().readText()
                }.orEmpty()
            } else {
                File(pathOrUri).readText()
            }

            val hint = formatHint ?: if (pathOrUri.startsWith("content://")) null else File(pathOrUri).extension
            LyricsParser.parse(content, hint).copy(sourcePath = pathOrUri)
        }.getOrDefault(LyricsDocument())
    }

    private fun buildTrackLabel(stem: String, file: File): String {
        val extension = file.extension.uppercase()
        val suffix = file.name
            .removePrefix(stem)
            .substringBeforeLast('.', "")
            .trim('.', '-', '_', ' ')

        if (suffix.isBlank()) {
            return if (file.extension.equals("lrc", ignoreCase = true)) {
                "Synced Lyrics ($extension)"
            } else {
                "Subtitles ($extension)"
            }
        }

        val parts = suffix.split('.', '-', '_')
        val langPart = parts.firstOrNull()?.trim()
        val displayName = langPart?.let { resolveLanguageDisplayName(it) } ?: suffix

        val extra = parts.drop(1).joinToString(" ").trim()
        return buildString {
            append(displayName)
            if (extra.isNotBlank()) {
                append(" ($extra)")
            } else {
                append(" [$extension]")
            }
        }
    }

    private fun extractLanguageCode(stem: String, file: File): String? {
        val suffix = file.name
            .removePrefix(stem)
            .substringBeforeLast('.', "")
            .trim('.', '-', '_', ' ')
        if (suffix.isBlank()) return null
        return suffix.split('.', '-', '_').firstOrNull()?.takeIf { it.length in 2..3 }
    }

    private fun resolveLanguageDisplayName(code: String): String {
        return try {
            val loc = Locale.forLanguageTag(code.replace('_', '-'))
            val name = loc.getDisplayLanguage(Locale.getDefault())
            if (name.isNotBlank() && !name.equals(code, ignoreCase = true)) {
                name.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }
            } else {
                code.uppercase()
            }
        } catch (_: Exception) {
            code.uppercase()
        }
    }
}
