package com.localdownloader.media.lyrics

data class LyricLine(
    val startTimeMs: Long,
    val endTimeMs: Long? = null,
    val text: String,
)

data class LyricsDocument(
    val lines: List<LyricLine> = emptyList(),
    val isSynced: Boolean = true,
    val title: String? = null,
    val artist: String? = null,
    val album: String? = null,
    val offsetMs: Long = 0L,
    val sourcePath: String? = null,
    val trackLabel: String? = null,
) {
    val isEmpty: Boolean
        get() = lines.isEmpty() || lines.all { it.text.isBlank() }

    fun getActiveIndex(positionMs: Long): Int {
        if (lines.isEmpty()) return -1
        if (positionMs < lines.first().startTimeMs) return -1

        var low = 0
        var high = lines.size - 1
        var candidate = -1

        while (low <= high) {
            val mid = (low + high) ushr 1
            val line = lines[mid]
            if (line.startTimeMs <= positionMs) {
                candidate = mid
                low = mid + 1
            } else {
                high = mid - 1
            }
        }
        return candidate
    }
}

data class LyricsTrackOption(
    val id: String,
    val label: String,
    val filePath: String,
    val language: String? = null,
    val isAutoGenerated: Boolean = false,
)
