package com.localdownloader.worker

object WorkerKeys {
    const val TASK_ID = "task_id"
    const val URL = "url"
    const val FORMAT_ID = "format_id"
    const val OUTPUT_TEMPLATE = "output_template"
    const val EXTRACTOR_ARGS = "extractor_args"
    const val FALLBACK_EXTRACTOR_ARGS = "fallback_extractor_args"
    const val LOAD_INFO_JSON_PATH = "load_info_json_path"
    const val USER_AGENT_HEADER = "user_agent_header"
    const val YOUTUBE_AUTH_ENABLED = "youtube_auth_enabled"
    const val COOKIES_PATH = "youtube_cookies_path"
    const val YOUTUBE_PO_TOKEN = "youtube_po_token"
    const val YOUTUBE_PO_TOKEN_CLIENT_HINT = "youtube_po_token_client_hint"
    const val YOUTUBE_DATA_SYNC_ID = "youtube_data_sync_id"
    const val MERGE_OUTPUT_FORMAT = "merge_output_format"
    const val PREFERRED_VIDEO_HEIGHT = "preferred_video_height"
    const val DOWNLOAD_VIDEO_ONLY = "download_video_only"
    const val PLAYLIST_ENABLED = "playlist_enabled"
    const val DOWNLOAD_SUBTITLES = "download_subtitles"
    const val EMBED_SUBTITLES = "embed_subtitles"
    const val EMBED_METADATA = "embed_metadata"
    const val EMBED_THUMBNAIL = "embed_thumbnail"
    const val WRITE_THUMBNAIL = "write_thumbnail"
    const val EXTRACT_AUDIO = "extract_audio"
    const val AUDIO_FORMAT = "audio_format"
    const val AUDIO_BITRATE = "audio_bitrate"
    const val TITLE_HINT = "title_hint"
    const val PLAYLIST_ITEM_INDEX = "playlist_item_index"
    const val PLAYLIST_FOLDER_NAME = "playlist_folder_name"

    const val PROGRESS_PERCENT = "progress_percent"
    const val ERROR_MESSAGE = "error_message"
    const val OUTPUT_PATH = "output_path"
    const val TERMINAL_STATUS = "terminal_status"
}
