package com.localdownloader.downloader

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse

class FormatExtractorParsingTest {

    @Test
    fun inferParsedCodecs_keepsAudioOnlyContainerWhenCodecMetadataMissing() {
        val codecs = inferParsedCodecs(
            extension = "mp3",
            resolution = null,
            rawVideoCodec = null,
            rawAudioCodec = null,
            note = "audio only",
        )

        assertEquals("none", codecs.videoCodec)
        assertEquals("unknown", codecs.audioCodec)
        assertFalse(
            shouldIgnoreParsedFormat(
                formatId = "best",
                extension = "mp3",
                note = "audio only",
                resolvedVideoCodec = codecs.videoCodec,
                resolvedAudioCodec = codecs.audioCodec,
            ),
        )
    }

    @Test
    fun inferParsedCodecs_keepsVideoOnlyEntryWhenResolutionExistsButCodecMetadataMissing() {
        val codecs = inferParsedCodecs(
            extension = "mp4",
            resolution = "720p",
            rawVideoCodec = null,
            rawAudioCodec = null,
            note = "video only",
        )

        assertEquals("unknown", codecs.videoCodec)
        assertEquals("none", codecs.audioCodec)
        assertFalse(
            shouldIgnoreParsedFormat(
                formatId = "video-720",
                extension = "mp4",
                note = "video only",
                resolvedVideoCodec = codecs.videoCodec,
                resolvedAudioCodec = codecs.audioCodec,
            ),
        )
    }

    @Test
    fun analyzeProcessTimeoutMillis_usesLongerDefaultTimeout() {
        assertEquals(DEFAULT_ANALYZE_PROCESS_TIMEOUT_MILLIS, analyzeProcessTimeoutMillis(5))
        assertEquals(EXTENDED_ANALYZE_PROCESS_TIMEOUT_MILLIS, analyzeProcessTimeoutMillis(15))
    }

    @Test
    fun parseSubtitles_correctlyExtractsNativeAndAutoSubtitles() {
        val jsonString = """
            {
                "en": [
                    { "ext": "vtt", "name": "English", "url": "https://example.com/en.vtt" }
                ],
                "es": [
                    { "ext": "vtt", "name": "Spanish", "url": "https://example.com/es.vtt" }
                ]
            }
        """.trimIndent()
        val jsonElement = kotlinx.serialization.json.Json.parseToJsonElement(jsonString) as kotlinx.serialization.json.JsonObject
        val tracks = parseSubtitles(jsonElement, isAutoGenerated = false)

        assertEquals(2, tracks.size)
        assertEquals("en", tracks[0].code)
        assertEquals("English", tracks[0].name)
        assertEquals("vtt", tracks[0].extension)
        assertFalse(tracks[0].isAutoGenerated)

        assertEquals("es", tracks[1].code)
        assertEquals("Spanish", tracks[1].name)
    }
}
