package com.localdownloader.utils

import com.localdownloader.domain.models.CookieProfile
import java.net.URI

object CookieTextCodec {
    private const val NETSCAPE_HEADER = "# Netscape HTTP Cookie File"
    private const val GENERATED_BY = "# Generated by Video Downloader"
    private val YOUTUBE_RELATED_HOSTS = setOf(
        "youtube.com",
        "youtu.be",
        "google.com",
        "googlevideo.com",
        "ytimg.com",
        "ggpht.com",
        "doubleclick.net",
        "youtube-nocookie.com",
    )
    const val COOKIE_USER_AGENT =
        "Mozilla/5.0 (Linux; Android 14; Mobile) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36"

    fun normalizeUrl(input: String): String? {
        val raw = input.trim()
        if (raw.isBlank()) return null
        val candidate = if (raw.startsWith("http://") || raw.startsWith("https://")) raw else "https://$raw"
        return runCatching {
            val uri = URI(candidate)
            val host = uri.host?.trim()?.removePrefix(".")?.ifBlank { null } ?: return null
            val scheme = uri.scheme?.ifBlank { "https" } ?: "https"
            val path = uri.path?.takeIf { it.isNotBlank() && it != "/" }.orEmpty()
            buildString {
                append(scheme)
                append("://")
                append(host)
                append(path)
            }
        }.getOrNull()
    }

    fun inferUrl(rawText: String): String? {
        rawText.lineSequence()
            .map { it.trim() }
            .firstOrNull { it.startsWith("# http://") || it.startsWith("# https://") }
            ?.removePrefix("#")
            ?.trim()
            ?.let(::normalizeUrl)
            ?.let { return it }

        rawText.lineSequence()
            .map { it.trim() }
            .firstOrNull { it.isNotBlank() && !it.startsWith("#") }
            ?.split(Regex("\\s+"))
            ?.firstOrNull()
            ?.removePrefix(".")
            ?.takeIf { it.isNotBlank() }
            ?.let { return normalizeUrl(it) }

        return null
    }

    fun buildStoredText(url: String, rawText: String): String {
        val normalizedUrl = normalizeUrl(url).orEmpty()
        val sanitizedBody = rawText.lineSequence()
            .map { it.trimEnd() }
            .filterNot {
                it.equals(NETSCAPE_HEADER, ignoreCase = true) ||
                it.startsWith("# http://") ||
                it.startsWith("# https://") ||
                it.equals(GENERATED_BY, ignoreCase = true)
            }
            .joinToString("\n")
            .trim()

        return buildString {
            append(NETSCAPE_HEADER)
            append('\n')
            append("# ")
            append(normalizedUrl)
            append('\n')
            append(GENERATED_BY)
            if (sanitizedBody.isNotBlank()) {
                append('\n')
                append(sanitizedBody)
            }
        }.trim()
    }

    fun buildCombinedExport(entries: List<CookieProfile>): String {
        val body = entries
            .sortedByDescending { it.updatedAtEpochMs }
            .flatMap { entry ->
                buildList {
                    add("# ${normalizeUrl(entry.url).orEmpty()}")
                    addAll(extractCookieLines(entry.cookiesText))
                }
            }
            .joinToString("\n")
            .trim()

        return buildString {
            append(NETSCAPE_HEADER)
            append('\n')
            append(GENERATED_BY)
            if (body.isNotBlank()) {
                append('\n')
                append(body)
            }
        }.trim()
    }

    fun buildRuntimeCookieFile(entries: List<CookieProfile>): String {
        val uniqueLines = linkedSetOf<String>()
        entries
            .sortedByDescending { it.updatedAtEpochMs }
            .flatMap { extractCookieLines(it.cookiesText) }
            .forEach { line ->
                uniqueLines += line
            }

        return buildString {
            append(NETSCAPE_HEADER)
            append('\n')
            append(GENERATED_BY)
            if (uniqueLines.isNotEmpty()) {
                append('\n')
                append(uniqueLines.joinToString("\n"))
            }
        }.trim()
    }

    fun previewText(cookiesText: String, maxLines: Int = 4): String {
        return cookiesText.lineSequence()
            .filterNot { it.equals(NETSCAPE_HEADER, ignoreCase = true) }
            .take(maxLines)
            .joinToString("\n")
    }

    fun findBestMatch(entries: List<CookieProfile>, targetUrl: String): CookieProfile? {
        return findRelevantProfiles(entries, targetUrl).firstOrNull()
    }

    fun findRelevantProfiles(entries: List<CookieProfile>, targetUrl: String): List<CookieProfile> {
        val targetHost = normalizeUrl(targetUrl)?.let(::hostOf) ?: return emptyList()
        val youtubeTarget = isYoutubeFamilyHost(targetHost)
        return entries
            .filter { entry ->
                val entryHost = hostOf(entry.url)
                targetHost == entryHost ||
                    targetHost.endsWith(".$entryHost") ||
                    entryHost.endsWith(".$targetHost") ||
                    (youtubeTarget && isYoutubeFamilyHost(entryHost))
            }
            .sortedByDescending { hostOf(it.url).length }
    }

    fun fromCookieHeader(url: String, header: String): String {
        val normalizedUrl = normalizeUrl(url).orEmpty()
        val uri = URI(normalizedUrl)
        val host = (uri.host ?: "").removePrefix(".")
        val secure = if (uri.scheme.equals("https", ignoreCase = true)) "TRUE" else "FALSE"
        val body = header.split(';')
            .map { it.trim() }
            .filter { it.contains('=') }
            .joinToString("\n") { chunk ->
                val name = chunk.substringBefore('=').trim()
                val value = chunk.substringAfter('=', "").trim()
                ".${host}\tTRUE\t/\t$secure\t0\t$name\t$value"
            }
        return buildStoredText(normalizedUrl, body)
    }

    private fun hostOf(url: String): String {
        return runCatching { URI(normalizeUrl(url)).host.orEmpty().removePrefix(".") }.getOrDefault("")
    }

    private fun extractCookieLines(rawText: String): List<String> {
        return rawText.lineSequence()
            .map { it.trim() }
            .filter { line ->
                line.isNotBlank() &&
                    !line.equals(NETSCAPE_HEADER, ignoreCase = true) &&
                    !line.startsWith("#")
            }
            .toList()
    }

    private fun isYoutubeFamilyHost(host: String): Boolean {
        return YOUTUBE_RELATED_HOSTS.any { related ->
            host == related || host.endsWith(".$related")
        }
    }
}
